version: "4"
services:

  car-rental-api:
    container_name: car-rental-api
    image: car-rental-api
    ports:
      - "8080:8080"
      - "9251:9251"
    environment:
      - DEBUG_PORT=9251
    build:
      context: car-rental-api

  car-rental-manager:
    container_name: car-rental-manager
    image: car-rental-manager
    ports:
      - "8081:8081"
      - "9252:9252"
    environment:
      - DEBUG_PORT=9252
    build:
      context: car-rental-manager
