version: "4"
services:

  car-rental-api:
    container_name: car-rental-api
    image: car-rental-api
    ports:
      - "8080:8080"
      - "9251:9251"
    environment:
      - DEBUG_PORT=9251
    build:
      context: car-rental-api

  car-rental-manager:
    container_name: car-rental-manager
    image: car-rental-manager
    ports:
      - "8081:8081"
      - "9252:9252"
    environment:
      - DEBUG_PORT=9252
    build:
      context: car-rental-manager

#  tempo:
#    container_name: grafana-tempo
#    image: grafana/tempo:2.2.2
#    command: [ "-config.file=/etc/tempo.yaml" ]
#    volumes:
#      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
#      - ./docker/tempo/tempo-data:/tmp/tempo
#    ports:
#      - "3110:3100"  # Tempo
#      - "9411:9411" # zipkin
#
#  loki:
#    container_name: grafana-loki
#    image: grafana/loki:main
#    command: [ "-config.file=/etc/loki/local-config.yaml" ]
#    ports:
#      - "3100:3100"
#
#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:v2.46.0
#    command:
#      - --enable-feature=exemplar-storage
#      - --config.file=/etc/prometheus/prometheus.yml
#    volumes:
#      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#    ports:
#      - "9090:9090"
#
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:10.1.0
#    volumes:
#      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#    ports:
#      - "3000:3000"
