version: "4"
services:

  car-rental-api:
    container_name: car-rental-api
    image: car-rental-api
    ports:
      - "8080:8080" # port for REST API
      - "9251:9251" # port for remote debug from localhost
    environment:
      - DEBUG_PORT=9251
    build:
      context: car-rental-api

  car-rental-manager:
    container_name: car-rental-manager
    image: car-rental-manager
    ports:
      - "8081:8081" # port for REST API
      - "9252:9252" # port for remote debug from localhost
    environment:
      - DEBUG_PORT=9252
    build:
      context: car-rental-manager

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.0
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000" # port for Grafana UI app

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.46.0
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090" # port to receive metrics from Zipkin Brave reporter + Zipkin's UI

  grafana-tempo:
    container_name: grafana-tempo
    image: grafana/tempo:2.2.2
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # port to retrieve traces by Grafana
      - "9411:9411"  # port to receive traces from Zipkin Brave reporter

  loki:
    container_name: loki
    image: grafana/loki:main
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100" # port to receive logs